from fastapi import APIRouter, HTTPException
from models.schemas import Log
from services.log_repository import LogRepository
from typing import List

router = APIRouter(prefix="/api", tags=["logs"])


@router.get("/logs", response_model=List[Log])
async def get_logs():
    """
    Retrieve all decision logs from database.
    Logs are sorted by timestamp (newest first).
    
    Returns:
        List of all logs
    """
    try:
        logs = LogRepository.get_all()
        return logs
    except Exception as e:
        raise HTTPException(status_code=500, detail="Failed to retrieve logs")


@router.get("/logs/agent/{agent_name}", response_model=List[Log])
async def get_logs_by_agent(agent_name: str):
    """
    Retrieve logs generated by a specific agent.
    
    Args:
        agent_name: Name of the agent (e.g., 'parser_agent', 'planner_agent')
        
    Returns:
        List of logs from that agent
    """
    try:
        logs = LogRepository.get_by_agent(agent_name)
        return logs
    except Exception as e:
        raise HTTPException(status_code=500, detail="Failed to retrieve logs")
